<br>
# Numerical Python (NumPy)
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- implements all the heavy lifting in C language which is much faster.
- useful linear algebra, Fourier transform, and random number capabilities
- Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. 
- Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.


# ndarray object
The ndarray (pronounced N D array) object is the main object for representing your array. This object can handle multi-dimensional array of any size that your memory can store. The biggest differences between a Python list and a ndarray object are these:

- ndarray is a fixed size array while list has a dynamic size. When you reshare a ndarray a new object is created with the new shape and the old object is deleted from memory.
- ndarray allows mathematical and logical operations on complete multi-dimensional arrays. With a Python list you will have to iterate over the sequence which take more time and code.
 
- ndarray has homogeneous data type for the complete array while Python list can contain multiple data types within a single array.


http://www.numpy.org/


In [4]:
import numpy as np

<br>
## Creating and initialize Arrays

Create a list and convert it to a numpy array

In [5]:
my_list = [1, 2, 3,4,5]
x = np.array(my_list)
x

array([1, 2, 3, 4, 5])

<br>
pass list directly

In [6]:
array_1 = np.array([6, 7, 8, 9])
array_1

array([6, 7, 8, 9])

<br>
list of lists to create a multidimensional array.

In [7]:
array_2 = np.array([[7, 8, 9], [10, 11, 12]])
array_2

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
create with `arange` type.

##### np.arange([start,] stop[, step,], dtype=None)

In [8]:
array_3 = np.arange(0, 30, 2) # start at 0 stop before 30 with steps of 2
array_3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`linspace` create array evenly spaced numbers over a specified interval.

In [9]:
array_4 = np.linspace(0, 3, 9) # return 9 evenly spaced values from 0 to 3
array_4

array([ 0.   ,  0.375,  0.75 ,  1.125,  1.5  ,  1.875,  2.25 ,  2.625,  3.   ])

<br>
- shape method return the dimensions of the array. (rows, columns)
- dtype method return the type
- ndim return number of diminsion 
- size return array size
- len return number of rows

In [10]:
print(array_1)
print(array_2)


print(array_1.shape)
print(array_2.shape)

print(array_1.dtype)

print(array_1.ndim)
print(array_2.ndim)

print(array_1.size)
print(array_1.itemsize)
print(array_1.size * array_1.itemsize, "bytes") 
print (len(array_1))
print (len(array_2))

[6 7 8 9]
[[ 7  8  9]
 [10 11 12]]
(4,)
(2, 3)
int32
1
2
4
4
16 bytes
4
2


<br>
`reshape` returns an array with the same data with a new shape. new diminsion must match old diminsion 

In [11]:
array_3 = np.arange(0, 30, 2) # start at 0 stop before 30 with steps of 2
print (array_3)
array_3 = array_3.reshape(3, 5) # reshape array to be 3x5
array_3

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`resize` changes the shape and size of array in-place. new diminsion must match old diminsion 

In [12]:
array_4 = np.linspace(0, 3, 9) # return 9 evenly spaced values from 0 to 3
print(array_4)
array_4.resize(3, 3)
array_4

[ 0.     0.375  0.75   1.125  1.5    1.875  2.25   2.625  3.   ]


array([[ 0.   ,  0.375,  0.75 ],
       [ 1.125,  1.5  ,  1.875],
       [ 2.25 ,  2.625,  3.   ]])

<br>
`ones` creates a new array of given shape and type, filled with ones.

In [13]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

<br>
`zeros` creates a new array of given shape and type, filled with zeros.

In [14]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

<br>
`eye` creates a 2-D array with ones on the diagonal and zeros elsewhere.

In [15]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<br>
`diag` extracts a diagonal  array.

In [16]:
print (array_4)
np.diag(array_4)

[[ 0.     0.375  0.75 ]
 [ 1.125  1.5    1.875]
 [ 2.25   2.625  3.   ]]


array([ 0. ,  1.5,  3. ])

<br>
Create an array using repeating list (or see `np.tile`)

In [17]:
np.array([1, 2, 3] * 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
create array and repeat elements n times .

In [18]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [19]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print (x)
print (y)

[1 2 3]
[4 5 6]


In [20]:
print(x + 1) # elementwise constant addition     [1 2 3] + 1 = [2 3  4]
print(x / 3) # elementwise constant addition     [1 2 3] / 3 = [0.33333333  0.66666667  1. ]

[2 3 4]
[ 0.33333333  0.66666667  1.        ]


In [21]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [22]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [23]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


## Odd or even

In [24]:
print (x)
x % 2 == 0

[1 2 3]


array([False,  True, False], dtype=bool)

<br>
**Dot Product:**  
np.dot 

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
    arrays to inner product of vectors:
    
$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [25]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [26]:
A = np.random.randint(1,10,(3,3))
B = np.random.randint(1,10,(3,3))
print("A:\n==")
print(A)
print("B:\n==")
print(B)

A:
==
[[2 4 5]
 [1 1 1]
 [2 4 7]]
B:
==
[[8 7 9]
 [1 5 8]
 [9 5 2]]


In [27]:
C = A.dot(B)
print(C)

[[65 59 60]
 [18 17 19]
 [83 69 64]]


<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [28]:
z = np.array([-2, -2, -2, 3, 3])

In [29]:
z.sum()

0

In [30]:
z.max()

3

In [31]:
z.min()

-2

In [32]:
z.mean()

0.0

In [33]:
z.std()

2.4494897427831779

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [34]:
z.argmax()

3

In [35]:
z.argmin()

0

<br>
## Indexing / Slicing
Remember that indexing starts at 0.

### 1D Indexing

In [36]:
array_1 = np.array(range(5000000))
array_1

array([      0,       1,       2, ..., 4999997, 4999998, 4999999])

In [37]:
array_1[-1]

4999999

In [38]:
array_1[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
array_1[1:10:2]

array([1, 3, 5, 7, 9])

### 2D Indexing

In [40]:
list_1 = [[i+l for l in range(2000)] for i in range(2000)]
array_1 = np.array(list_1)
array_1

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [   1,    2,    3, ..., 1998, 1999, 2000],
       [   2,    3,    4, ..., 1999, 2000, 2001],
       ..., 
       [1997, 1998, 1999, ..., 3994, 3995, 3996],
       [1998, 1999, 2000, ..., 3995, 3996, 3997],
       [1999, 2000, 2001, ..., 3996, 3997, 3998]])

In [41]:
#get the second row
array_1[2]

array([   2,    3,    4, ..., 1999, 2000, 2001])

In [42]:
#get the first item in the second row
array_1[2][0]

2

In [43]:
#get the first item in the second row
array_1[2,0]

2

In [44]:
array_1[1:5,0]

array([1, 2, 3, 4])

In [45]:
array_1[1:5,0:5]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

### filtering

In [46]:
array_1 = np.array(range(10))
print(array_1)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
mask = np.array([True, False, False, False, False, False, False, False, False, True])
print(array_1[mask])

[0 9]


In [48]:
array_1[array_1 < 5]

array([0, 1, 2, 3, 4])

In [49]:
array_1[array_1 % 2 == 0]

array([0, 2, 4, 6, 8])

### To apply a function to a numpy array, you have to vectorize the function.

In [50]:
def isodd(n):
    return bool(n % 2)

visodd = np.vectorize(isodd)

In [51]:
array_1[visodd(array_1)]

array([1, 3, 5, 7, 9])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


In [52]:
x = np.arange(36)
x.resize((6, 6))
print (x)
y = x[:3,:3]
y

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [53]:
y[:] = 0
y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`x` has also been changed!

In [54]:
x

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
To avoid this, use `x.copy` to create a copy that will not affect the original array

In [55]:
x_copy = x.copy()
x_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Now when x_copy is modified, x will not be changed.

In [56]:
x_copy[:] = 10
print(x_copy, '\n')
print(x)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [57]:
x = np.random.randint(0, 10, (4,3))
x

array([[2, 3, 5],
       [8, 8, 8],
       [2, 3, 6],
       [2, 2, 2]])

<br>
Iterate by row:

In [58]:
for row in x:
    print(row)

[2 3 5]
[8 8 8]
[2 3 6]
[2 2 2]


<br>
Iterate by index:

In [59]:
for i in range(len(x)):
    print(x[i])

[2 3 5]
[8 8 8]
[2 3 6]
[2 2 2]


<br>
Iterate by row and index:

In [60]:
for i, row in enumerate(x):
    print('row', i, 'is', row)

row 0 is [2 3 5]
row 1 is [8 8 8]
row 2 is [2 3 6]
row 3 is [2 2 2]


<br>
Use `zip` to iterate over multiple iterables.

In [61]:
y = x**2
y

array([[ 4,  9, 25],
       [64, 64, 64],
       [ 4,  9, 36],
       [ 4,  4,  4]], dtype=int32)

In [62]:
for i, j in zip(x, y):
    print(i,'+',j,'=',i+j)

[2 3 5] + [ 4  9 25] = [ 6 12 30]
[8 8 8] + [64 64 64] = [72 72 72]
[2 3 6] + [ 4  9 36] = [ 6 12 42]
[2 2 2] + [4 4 4] = [6 6 6]


In [63]:
# Regular Python
python_list_1 = range(1,1000)
python_list_2 = range(1,1000)

#Numpy
numpy_list_1 = np.arange(1,1000)
numpy_list_2 = np.arange(1,1000)


In [64]:
%%capture timeit_python
%%timeit
# Regular Python
[(x + y) for x, y in zip(python_list_1, python_list_2)]
[(x - y) for x, y in zip(python_list_1, python_list_2)]
[(x * y) for x, y in zip(python_list_1, python_list_2)]
[(x / y) for x, y in zip(python_list_1, python_list_2)];

In [65]:
print (timeit_python)

1000 loops, best of 3: 257 us per loop



In [66]:
%%capture timeit_numpy
%%timeit
#Numpy
numpy_list_1 + numpy_list_2
numpy_list_1 - numpy_list_2
numpy_list_1 * numpy_list_2
numpy_list_1 / numpy_list_2;

In [67]:
print (timeit_numpy)

The slowest run took 17.91 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.11 us per loop



# References:
    
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
- https://docs.scipy.org/doc/numpy-1.13.0/reference/
- http://matplotlib.org/